--SSMS
CREATE TABLE studies 
(
PNAME VARCHAR(20), 
INSTITUTE VARCHAR(20), 
COURSE VARCHAR(20), 
COURSE_FEE INT
)

INSERT INTO studies
SELECT 'ANAND', 'SABHARI', 'PGDCA', 4500 UNION ALL
SELECT 'ALTAF', 'COIT', 'DCA', 7200 UNION ALL
SELECT 'JULIANA', 'BDPS', 'MCA', 22000 UNION ALL
SELECT 'KAMALA', 'PRAGATHI', 'DCA', 5000 UNION ALL
SELECT 'MARY', 'SABHARI', 'PGDCA', 4500 UNION ALL
SELECT 'NELSON', 'PRAGATHI', 'DAP', 6200 UNION ALL
SELECT 'PATRICK', 'PRAGATHI', 'DCAP', 5200 UNION ALL
SELECT 'QADIR', 'APPLE', 'HDCA', 14000 UNION ALL
SELECT 'RAMESH', 'SABHARI', 'PGDCA', 4500 UNION ALL
SELECT 'REBECCA', 'BRILLIANT', 'DCAP', 11000 UNION ALL
SELECT 'REMITHA', 'BDPS', 'DCS', 6000 UNION ALL
SELECT 'REVATHI', 'SABHARI', 'DAP', 5000 UNION ALL
SELECT 'VIJAYA', 'BDPS', 'DCA', 48000
GO
SELECT * FROM studies


CREATE TABLE software 
(
PNAME VARCHAR(20),
TITLE VARCHAR(20),
DEVELOPIN VARCHAR(20),
SCOST DECIMAL(10,2),
DCOST INT, SOLD INT
)

INSERT INTO software
SELECT 'MARY','README','CPP',300, 1200, 84 UNION ALL
SELECT 'ANAND','PARACHUTES','BASIC',399.95, 6000, 43 UNION ALL
SELECT 'ANAND','VIDEO TITLING','PASCAL',7500, 16000, 9 UNION ALL
SELECT 'JULIANA','INVENTORY','COBOL',3000, 3500, 0 UNION ALL
SELECT 'KAMALA','PAYROLL PKG.','DBASE',9000, 20000, 7 UNION ALL
SELECT 'MARY','FINANCIAL ACCT.','ORACLE',18000, 85000, 4 UNION ALL
SELECT 'MARY','CODE GENERATOR','C',4500, 20000, 23 UNION ALL
SELECT 'PATTRICK','README','CPP',300, 1200, 84 UNION ALL
SELECT 'QADIR','BOMBS AWAY','ASSEMBLY',750, 3000, 11 UNION ALL
SELECT 'QADIR','VACCINES','C',1900, 3100, 21 UNION ALL
SELECT 'RAMESH','HOTEL MGMT.','DBASE',13000, 35000, 4 UNION ALL
SELECT 'RAMESH','DEAD LEE','PASCAL',599.95, 4500, 73 UNION ALL
SELECT 'REMITHA','PC UTILITIES','C',725, 5000, 51 UNION ALL
SELECT 'REMITHA','TSR HELP PKG.','ASSEMBLY',2500, 6000, 7 UNION ALL
SELECT 'REVATHI','HOSPITAL MGMT.','PASCAL',1100, 75000, 2 UNION ALL
SELECT 'VIJAYA','TSR EDITOR','C',900, 700, 6
Go
select * from software

CREATE TABLE programmer 
(
PNAME VARCHAR(20),
DOB date,
DOJ date,
GENDER VARCHAR(20),
PROF1 VARCHAR(20),
PROF2 VARCHAR(20),
SALARY INT
)

INSERT INTO programmer
SELECT 'ANAND','12-Apr-66','21-Apr-92','M','PASCAL','BASIC',3200 UNION ALL
SELECT 'ALTAF','02-Jul-64','13-Nov-90','M','CLIPPER','COBOL',2800 UNION ALL
SELECT 'JULIANA','31-Jan-60','21-Apr-90','F','COBOL','DBASE',3000 UNION ALL
SELECT 'KAMALA','30-Oct-68','02-Jan-92','F','C','DBASE',2900 UNION ALL
SELECT 'MARY','24-Jun-70','01-Feb-91','F','CPP','ORACLE',4500 UNION ALL
SELECT 'NELSON','11-Sep-85','11-Oct-89','M','COBOL','DBASE',2500 UNION ALL
SELECT 'PATTRICK','10-Nov-65','21-Apr-90','M','PASCAL','CLIPPER',2800 UNION ALL
SELECT 'QADIR','31-Aug-65','21-Apr-91','M','ASSEMBLY','C',3000 UNION ALL
SELECT 'RAMESH','03-May-67','28-Feb-91','M','PASCAL','DBASE',3200 UNION ALL
SELECT 'REBECCA','01-Jan-67','01-Dec-90','F','BASIC','COBOL',2500 UNION ALL
SELECT 'REMITHA','19-Apr-70','20-Apr-93','F','C','ASSEMBLY',3600 UNION ALL
SELECT 'REVATHI','02-Dec-69','02-Jan-92','F','PASCAL','BASIC',3700 UNION ALL
SELECT 'VIJAYA','14-Dec-65','02-May-92','F','FOXPRO','C',3500
Go
SELECT * FROM programmer


-- Questions SQL Assignments
--1
SELECT AVG(SCOST) FROM software WHERE DEVELOPIN = 'PASCAL'

--2
SELECT PNAME AS NAME , DATEDIFF (YY,DOB,GETDATE()) FROM [dbo].[programmer]

--3
SELECT PNAME AS NAME FROM studies WHERE COURSE = 'DAP'

--4
SELECT PNAME AS NAMES, DOB FROM programmer WHERE MONTH ([DOB]) LIKE 'January'  
 
 --5
 SELECT MAX(SOLD) FROM software

 --6
 SELECT MIN(COURSE_FEE) FROM studies

 --7
 SELECT COUNT(*) FROM studies WHERE COURSE = 'PGDCA'

 --8
 SELECT SUM(SCOST*SOLD) FROM software WHERE DEVELOPIN='C'

 --9
 SELECT [DEVELOPIN] FROM software WHERE PNAME = 'RAMESH'

 --10
 SELECT PNAME,[COURSE_FEE] FROM studies WHERE INSTITUTE = 'SABHARI' GROUP BY PNAME,COURSE_FEE

 --11
 SELECT PNAME,[COURSE_FEE] FROM studies WHERE INSTITUTE = 'SABHARI' GROUP BY PNAME,[COURSE_FEE] HAVING COURSE_FEE>4500

 --12
 SELECT*FROM software WHERE (SCOST*SOLD) >2000
 --13
 SELECT TITLE, SUM(SCOST*SOLD) AS TOTAL_REVENUE FROM software GROUP BY TITLE HAVING SUM(SCOST*SOLD)>2000

 --14
 SELECT TITLE,SUM(SCOST*SOLD) AS TOTAL_REVENUE, DCOST FROM software GROUP BY TITLE ,DCOST HAVING SUM(SCOST*SOLD)>DCOST

 --15
 SELECT DEVELOPIN,TITLE,MAX(SCOST) FROM software GROUP BY TITLE, DEVELOPIN HAVING DEVELOPIN= 'BASIC'

 --16
 select COUNT(DEVELOPIN) AS PACKAGES FROM software GROUP BY DEVELOPIN HAVING DEVELOPIN = 'DBASE'

--17
SELECT COUNT(1) FROM software WHERE DEVELOPIN= 'DBASE'

--18
SELECT COUNT(1) FROM studies WHERE INSTITUTE = 'PRAGATHI'

--19
SELECT COUNT(*) FROM studies WHERE COURSE_FEE>5000 AND COURSE_FEE<10000

--20
SELECT AVG(COURSE_FEE) AS AVG_CF, COURSE FROM studies GROUP BY COURSE

--21
SELECT AVG(COURSE_FEE) FROM studies

--22
SELECT * FROM programmer WHERE [PROF1]='C' OR [PROF2]='C'

--23
SELECT COUNT(*) FROM programmer WHERE [PROF1]='COBOL' OR PROF2='PASCAL' OR PROF2='COBOL' OR PROF1='PASCAL'

--24
SELECT COUNT(1) FROM programmer WHERE PROF1='COBOL' OR PROF2='PASCAL' OR PROF2='COBOL' OR PROF1='PASCAL'

--25
SELECT DATEDIFF(YY,DOB,GETDATE()), PNAME FROM programmer WHERE GENDER ='M' GROUP BY PNAME, DOB ORDER BY DATEDIFF(YY,DOB, GETDATE()) DESC

--26
SELECT AVG(DATEDIFF(YY,DOB,GETDATE())), PNAME FROM [dbo].[programmer] WHERE GENDER = 'F' GROUP BY DOB,PNAME

--27
SELECT DATEDIFF(YY,DOJ,GETDATE()) AS EXPERIENCE, PNAME FROM programmer ORDER BY DATEDIFF(YY,DOJ,GETDATE()) DESC

--28
SELECT * FROM programmer WHERE MONTH(DOB) = 10

--29
SELECT COUNT(*) FROM programmer WHERE GENDER='F'

--30
SELECT PROF1, PROF2 FROM programmer WHERE GENDER='F'

--31
SELECT SUM(SCOST*SOLD) AS SALES_VALUES ,PNAME AS PROGRAMMER FROM [dbo].[software]GROUP BY PNAME
SELECT PNAME, SUM(SCOST*SOLD) AS TotalSales FROM software GROUP BY PNAME

--32
SELECT SUM(SOLD) AS PACKAGESSOLD, PNAME AS PROGRAMMER FROM [dbo].[software] GROUP BY PNAME

--33
SELECT SUM(SCOST), PNAME, DEVELOPIN AS LANGUAGE FROM software GROUP BY DEVELOPIN, PNAME, SCOST

--34
SELECT DEVELOPIN, AVG(DCOST) AS AvgDevCost, AVG(SCOST) AS AvgSellCost 
,IIF(SUM(SOLD)<>0,sum(SCOST)/sum(SOLD),0) AS AvgPrCopy
FROM software GROUP BY DEVELOPIN

SELECT AVG(DCOST) AS AVG_d_C, AVG(SCOST) AS AVG_s_c, AVG(SCOST*SOLD) AS AVG_p_copy, DEVELOPIN AS _LANGUAGE FROM software
GROUP BY DEVELOPIN

--35
SELECT PNAME AS PROGRAMMER_NAME, MAX(DCOST), MIN(DCOST) FROM software GROUP BY PNAME

--36
SELECT INSTITUTE, COUNT(COURSE), AVG(COURSE_FEE) FROM studies GROUP BY INSTITUTE

--37
SELECT INSTITUTE, COUNT(PNAME) FROM studies GROUP BY INSTITUTE

--38
SELECT PNAME,GENDER FROM programmer GROUP BY GENDER,PNAME

--39
SELECT PNAME, SUM(DCOST) AS SumDCOST, SUM(SCOST*SOLD) AS SumSCOST-SUM(SCOST*SOLD), SUM(DCOST) AS SumDiffCOST
FROM software GROUP BY PNAME HAVING SUM(SCOST*SOLD)<SUM(DCOST)

-- OR

SELECT PNAME,TITLE FROM SOFTWARE ORDER BY PNAME,TITLE

--40
SELECT PNAME,DEVELOPIN AS PACKAGES FROM software GROUP BY DEVELOPIN, PNAME

SELECT COUNT(1) AS [NO OF PACKAGES] FROM software WHERE DEVELOPIN NOT IN ('C','CPP')

--41
SELECT COUNT(1) FROM software WHERE DCOST<1000

--42
select AVG(DCOST-SCOST) AS AVG_DIFFERENCE FROM software GROUP BY TITLE

--43
SELECT PNAME,SUM(SCOST) AS TIL_SCOST, SUM(DCOST) AS TIL_DCOST, SUM(DCOST-(SOLD*SCOST)) AS RECOVERED FROM software GROUP BY PNAME HAVING SUM(DCOST)>SUM(SOLD*SCOST)

--44
SELECT MAX(SALARY) as HIGHEST, MIN(SALARY) AS LOWEST, AVG(SALARY) AS AVGERAGE FROM programmer WHERE SALARY>2000

--45
SELECT TOP 1 PNAME, MAX(SALARY) AS MM_SALARY FROM programmer WHERE PROF1='C' OR PROF2='C' GROUP BY PNAME ORDER BY MM_SALARY DESC

--46
SELECT * FROM programmer WHERE SALARY=(SELECT MAX(SALARY) FROM programmer WHERE PROF1= 'COBOL' OR PROF2= 'COBOL' AND GENDER='F')

--47
SELECT MAX(SALARY) AS HIGHEST_PAID_PROGRAMMER, PROF1, PROF2, PNAME FROM programmer GROUP BY PROF1, PROF2,SALARY, PNAME ORDER BY MAX(SALARY) DESC

--48
SELECT TOP 1 PNAME,MIN(YEAR(GETDATE())-YEAR(DOJ)) AS EXPERIENCE FROM programmer GROUP BY PNAME ORDER BY EXPERIENCE

--49
SELECT TOP 1 MAX(DATEDIFF(YY,DOJ,GETDATE())) AS MOST_EXPERIENCED,PNAME,GENDER,PROF1,PROF2 FROM programmer WHERE PROF1='PASCAL' OR PROF2='PASCAL' GROUP BY DOJ,PNAME,GENDER,PROF1,PROF2 HAVING GENDER='M' ORDER BY  MAX(DATEDIFF(YY,DOJ,GETDATE())) DESC


--50. Which Language is known by only one Programmer? 
SELECT PROF1 FROM programmer GROUP BY PROF1 HAVING
PROF1 NOT IN (SELECT PROF2 FROM programmer)
AND COUNT (PROF1) = 1
UNION
SELECT PROF2 FROM programmer GROUP BY PROF2 HAVING
PROF2 NOT IN (SELECT PROF1 FROM programmer)
AND COUNT (PROF2) = 1

--51. Who is the Above Programmer Referred in 50?
SELECT*FROM programmer

--52. Who is the Youngest Programmer knowing DBASE?
SELECT TOP 1 PNAME,(YEAR(GETDATE())-YEAR(DOB)) AS AGE FROM programmer WHERE PROF1 = 'DBASE' OR PROF2='DBASE' ORDER BY AGE ASC

--53. Which Female Programmer earning more than 3000 does not know C, C++, 
--ORACLE or DBASE?
SELECT PNAME,GENDER FROM programmer WHERE SALARY>3000 AND GENDER='F'

--54. Which Institute has most number of Students?

SELECT TOP 1
S1.INSTITUTE,COUNT(PNAME) AS STUDENTS_NO FROM STUDIES AS S1 GROUP BY INSTITUTE ORDER BY STUDENTS_NO DESC

--55. What is the Costliest course? 
SELECT COURSE FROM studies WHERE COURSE_FEE=(SELECT MAX (COURSE_FEE) FROM studies)

--56. Which course has been done by the most of the Students?
SELECT TOP 1 WITH TIES
S1.COURSE, COUNT(PNAME) AS [NO OF STUDENT] FROM studies AS S1
GROUP BY COURSE ORDER BY [NO OF STUDENT] DESC

--57. Which Institute conducts costliest course. 
SELECT INSTITUTE FROM studies WHERE COURSE_FEE=(SELECT MAX(COURSE_FEE) FROM studies)

--58. Display the name of the Institute and Course, which has below AVG course fee. 
SELECT INSTITUTE,COURSE FROM STUDIES WHERE COURSE_FEE<(SELECT AVG(COURSE_FEE) FROM STUDIES)

--59. Display the names of the courses whose fees are within 1000 (+ or -) of the 
--Average Fee.
SELECT COURSE FROM studies WHERE COURSE_FEE<(SELECT AVG(COURSE_FEE) + 1000 FROM studies) AND COURSE_FEE<((SELECT AVG(COURSE_FEE) -1000 FROM studies))

--60. Which package has the Highest Development cost? 
SELECT TITLE FROM SOFTWARE WHERE DCOST=(SELECT MAX(DCOST) FROM SOFTWARE)

--61. Which course has below AVG number of Students? 
SELECT COURSE FROM studies GROUP BY COURSE HAVING COUNT(PNAME)<(SELECT AVG(TB.COUNT_PNAME) FROM (SELECT COUNT(PNAME) AS COUNT_PNAME FROM studies)TB)

--62. Which Package has the lowest selling cost? 
SELECT TITLE,SCOST FROM software WHERE SCOST=(SELECT MIN(SCOST) FROM software)

--63. Who Developed the Package that has sold the least number of copies? 
SELECT PNAME,SOLD FROM software WHERE SOLD=(SELECT MIN(SOLD) FROM software)

--64. Which language has used to develop the package, which has the highest 
--sales amount? 
SELECT DEVELOPIN FROM software WHERE SCOST=(SELECT MAX(SCOST) FROM software)

--65. How many copies of package that has the least difference between 
--development and selling cost where sold. 
SELECT SOLD,TITLE FROM software WHERE (DCOST-SCOST) = (SELECT MIN(DCOST-SCOST) FROM software)

--66. Which is the costliest package developed in PASCAL. 
SELECT TOP 1 TITLE,MAX(SCOST) AS COSTLIEST FROM software WHERE DEVELOPIN = 'PASCAL' GROUP BY TITLE ORDER BY COSTLIEST DESC

--67. Which language was used to develop the most number of Packages. 
SELECT TOP 1 WITH TIES DEVELOPIN, COUNT(*) AS [NO OF PACKAGES] FROM software GROUP BY DEVELOPIN ORDER BY COUNT(*) DESC

--68. Which programmer has developed the highest number of Packages? 
SELECT COUNT(DEVELOPIN) AS H_NO_P, PNAME AS PROGRAMMER FROM software GROUP BY PNAME ORDER BY COUNT(DEVELOPIN) DESC

--69. Who is the Author of the Costliest Package? 
SELECT DCOST AS COSTLIEST_P, PNAME AS AUTHOR FROM software WHERE DCOST=(SELECT MAX(DCOST) FROM software) GROUP BY PNAME, DCOST ORDER BY MAX(DCOST) DESC

--70. Display the names of the packages, which have sold less than the AVG 
--number of copies. 
SELECT SOLD AS AVG_C_P, DEVELOPIN AS PACKAGES, TITLE FROM software GROUP BY DEVELOPIN,SOLD, TITLE HAVING SOLD<(SELECT AVG(SOLD) FROM software) ORDER BY DEVELOPIN DESC

SELECT TITLE,SOLD,DEVELOPIN FROM Software
WHERE SOLD<(SELECT AVG(SOLD) FROM Software)

--71. Who are the authors of the Packages, which have recovered more than double the 
--Development cost? 
SELECT PNAME,TITLE FROM software WHERE SOLD*SCOST>2*DCOST

--72. Display the programmer Name and the cheapest packages developed by them in
--each language. 
SELECT PNAME AS PROGRAMMER_NAME, DCOST AS MIN_DCOST, DEVELOPIN AS PACKAGES FROM software WHERE DCOST=(SELECT MIN(DCOST) FROM software) GROUP BY DEVELOPIN , PNAME,DCOST ORDER BY DEVELOPIN

--73. Display the language used by each programmer to develop the Highest 
--Selling and Lowest-selling package. 
SELECT DEVELOPIN AS LANGUAGES, PNAME, (SCOST*SOLD) AS selling_package  FROM software  GROUP BY DEVELOPIN , PNAME,SOLD,SCOST ORDER BY (SCOST*SOLD) desc

SELECT PNAME, DEVELOPIN, 'HIGHEST' FROM Software 
WHERE SOLD IN (SELECT MAX(SOLD) FROM Software) UNION 
SELECT PNAME, DEVELOPIN, 'LOWEST' FROM Software WHERE SOLD IN 
(SELECT MIN(SOLD) FROM Software)

--74. Who is the youngest male Programmer born in 1965? 
SELECT DATEDIFF(YY,DOB,GETDATE()), PNAME AS PROGRAMMER , GENDER FROM programmer WHERE GENDER ='M' AND YEAR(DOB)=1965  GROUP BY DOB, PNAME, GENDER ORDER BY MIN( DATEDIFF(YY,DOB,GETDATE()))

SELECT PNAME, DOB FROM programmer WHERE DATEDIFF(DD,DOB,GETDATE())=
(SELECT MIN(DATEDIFF(DD,DOB,GETDATE())) FROM Programmer WHERE  year(DOB)=1965 AND GENDER='M')

--75. Who is the oldest Female Programmer who joined in 1992?
SELECT DATEDIFF(YY,DOJ,GETDATE()), PNAME AS PROGRAMMER , GENDER FROM programmer WHERE GENDER ='F' AND YEAR(DOJ)=1992 GROUP BY DOJ, PNAME, GENDER ORDER BY MIN( DATEDIFF(YY,DOJ,GETDATE()))

SELECT PNAME,DOB,YEAR(DOJ) FROM Programmer WHERE DATEDIFF(DD,DOB,GETDATE())=
(SELECT MAX(DATEDIFF(DD,DOB,GETDATE())) FROM Programmer WHERE YEAR(DOJ) ='1992');

--76. In which year was the most number of Programmers born. 
CREATE TABLE #TEMPY_M_pBORN (YOB INT, CNT INT)

INSERT INTO #TEMPY_M_pBORN
SELECT YEAR(DOB),COUNT(YEAR(DOB)) FROM programmer GROUP BY YEAR(DOB)

SELECT YOB, CNT FROM #TEMPY_M_pBORN
WHERE CNT= (SELECT MAX(CNT) FROM #TEMPY_M_pBORN)

--77. In which month did most number of programmers join? 
SELECT COUNT(DOJ) AS COUNTOF_DOJ , MONTH(DOJ) AS JOINED_MONTH_mj FROM PROGRAMMER GROUP BY DOJ ORDER BY COUNT(DOJ) DESC

CREATE TABLE #MOJ (MOJ INT , CNT INT)
INSERT INTO #MOJ
SELECT MONTH(DOJ),COUNT (MONTH(DOJ)) FROM PROGRAMMER GROUP BY MONTH(DOJ)

SELECT MOJ,CNT FROM #MOJ WHERE CNT=(SELECT MAX(CNT) FROM #MOJ)

--78. In which language are most of the programmer’s proficient.
CREATE TABLE #PCNT (PR VARCHAR(20), CNT INT)
CREATE TABLE #PsCNT (PRs VARCHAR(20), sCNT INT)

INSERT INTO #PCNT
SELECT PROF1, COUNT(PROF1) FROM programmer GROUP BY PROF1 UNION ALL
SELECT PROF2, COUNT(PROF2) FROM programmer GROUP BY PROF2

INSERT INTO #PsCNT
SELECT PR, SUM(CNT) FROM #PCNT GROUP BY PR

SELECT PRs, sCNT FROM #PsCNT WHERE sCNT = 
(SELECT MAX(sCNT) FROM #PsCNT)

--79. Who are the male programmers earning below the AVG salary of
--Female Programmers? 
SELECT PNAME,SALARY FROM PROGRAMMER  WHERE GENDER ='M' AND 
SALARY<(SELECT AVG(SALARY) FROM PROGRAMMER WHERE GENDER ='F')
SELECT*FROM programmer

--80. Who are the Female Programmers earning more than the Highest Paid?
SELECT PNAME,SALARY FROM PROGRAMMER  WHERE GENDER ='F' AND 
SALARY<(SELECT AVG(SALARY) FROM PROGRAMMER WHERE GENDER ='M')


SELECT MAX(SALARY) AS HIGHEST_PAID, GENDER , PNAME AS F_PROG FROM programmer WHERE GENDER = 'F' GROUP BY SALARY , PNAME,GENDER ORDER BY MAX(SALARY) DESC

--81
SELECT MAX(DATEDIFF(YY,DOJ,GETDATE())) AS PROFICIENT_LEVEL,PNAME FROM programmer  GROUP BY DOJ, PNAME  ORDER BY MAX(DATEDIFF(YY,DOJ,GETDATE()))

 CREATE TABLE #PCNT1 (PR VARCHAR(20), CNT INT)
CREATE TABLE #PsCNT1 (PRs VARCHAR(20), sCNT INT)

INSERT INTO #PCNT1
SELECT PROF1, COUNT(PROF1) FROM programmer GROUP BY PROF1 UNION ALL
SELECT PROF2, COUNT(PROF2) FROM programmer GROUP BY PROF2


INSERT INTO #PsCNT1
SELECT PR, SUM(CNT) FROM #PCNT GROUP BY PR

SELECT PRs, sCNT FROM #PsCNT1 WHERE sCNT = 
(SELECT MAX(sCNT) FROM #PsCNT1)


--82

SELECT PNAME,DOB,DOJ,PROF1,PROF2,AVG(SALARY) AS ALMOST_SAME FROM PROGRAMMER GROUP BY PNAME,DOB,DOJ,PROF1,PROF2 ,SALARY ORDER BY SALARY

SELECT A.PNAME, A.SALARY FROM Programmer A
INNER JOIN PROGRAMMER B ON A.SALARY= B.SALARY AND A.PNAME<>B.PNAME
ORDER BY A.SALARY

--83

SELECT  T1.SALARY,T1.GENDER , T2.*FROM  programmer AS T1  JOIN software AS T2 
ON T1.PNAME=T2.PNAME
 WHERE SALARY>3000 AND GENDER ='M'

 --OR
 --83
 SELECT * FROM software WHERE PNAME IN 
(SELECT PNAME FROM programmer WHERE SALARY>3000 AND GENDER='M')


--84
SELECT  T1.PROF1,T1.GENDER,T1.PROF2 , T2.DEVELOPIN ,T2.PNAME FROM  programmer AS T1  JOIN software AS T2 
ON T1.PNAME=T2.PNAME
 WHERE DEVELOPIN ='PASCAL' AND GENDER ='F'

SELECT PNAME  , DEVELOPIN AS SOFTWARE_DEVE, TITLE FROM software WHERE DEVELOPIN='PASCAL' GROUP BY PNAME,DEVELOPIN ,TITLE ----DOUBT JOIN

--85
SELECT [PNAME],[DOB],[DOJ],[GENDER],[PROF1],[PROF2],[SALARY] FROM programmer WHERE YEAR(DOJ)<1990

--86
SELECT SW.*,P.GENDER,ST.INSTITUTE FROM studies AS ST, software AS SW, programmer AS P
WHERE P.PNAME=SW.PNAME AND ST.PNAME=SW.PNAME AND
GENDER='F' AND INSTITUTE='PRAGATHI' AND DEVELOPIN='C'

SELECT DISTINCT T1.[GENDER],T2.[DEVELOPIN],T3.[INSTITUTE], T3.PNAME FROM [dbo].[programmer] AS T1 ,[dbo].[software] AS T2 , [dbo].[studies]AS T3 
WHERE DEVELOPIN='C' AND GENDER='F' AND INSTITUTE='PRAGATHI'

--87
SELECT INSTITUTE, COUNT(SW.TITLE) AS PKGCNT, COUNT(SW.SOLD) AS SALESCNT, SUM(SCOST*SOLD) AS SALVAL
FROM software AS SW JOIN studies AS ST 
ON SW.PNAME=ST.PNAME
GROUP BY INSTITUTE 

--88
CREATE TABLE #INST (INS VARCHAR(20), CNT INT)

INSERT INTO #INST
SELECT INSTITUTE, COUNT(PNAME) FROM studies GROUP BY INSTITUTE

SELECT DISTINCT SW.* FROM software AS SW, programmer AS PG, studies AS ST, #INST
WHERE DEVELOPIN='DBASE' AND GENDER='M' AND SW.PNAME = PG.PNAME 
AND INSTITUTE = INS AND CNT= (SELECT MAX(CNT) FROM #INST)

--89
SELECT S.*, YEAR(DOB),GENDER FROM Programmer p JOIN Software s 
ON s.PNAME=p.PNAME
WHERE
((GENDER='M' AND YEAR(DOB)<1965) AND (GENDER='F' AND YEAR(DOB)>1975))

--90
SELECT SW.*,PG.PROF1,PG.PROF2 from Software AS SW JOIN programmer AS PG  ON PG.PNAME = SW.PNAME
WHERE PG.PROF1 <> SW.DEVELOPIN AND PG.PROF2 <> SW.DEVELOPIN 

--91
SELECT T1.*, T2.INSTITUTE ,T3.GENDER FROM software AS T1 JOIN studies AS T2 
ON T1.PNAME = T2.PNAME JOIN  programmer AS T3 ON T2.PNAME=T3.PNAME 
WHERE GENDER='M' AND INSTITUTE ='SABHARI'

--92
SELECT PNAME FROM Programmer 
	WHERE PNAME NOT IN (SELECT PNAME from Software)

--93
SELECT SUM(SCOST) ,ST.INSTITUTE FROM Software s,Studies st 
WHERE s.PNAME=st.PNAME and INSTITUTE='APPLE' GROUP BY SCOST, INSTITUTE

--94
SELECT DISTINCT A.PNAME, A.DOJ FROM programmer AS A INNER JOIN programmer AS B
ON A.DOJ=B.DOJ WHERE A.PNAME<>B.PNAME ORDER BY A.DOJ

--95
SELECT DISTINCT A.PNAME, A.PROF2 FROM programmer AS A INNER JOIN programmer AS B
ON A.PROF2=B.PROF2 WHERE A.PNAME<>B.PNAME ORDER BY A.PROF2

--96
SELECT Studies.INSTITUTE,sum(Software.SOLD*Software.SCOST) from Software JOIN Studies 
	ON Studies.PNAME=Software.PNAME group by Studies.INSTITUTE

--97
SELECT INSTITUTE, SW.PNAME, DCOST FROM studies AS ST, software AS SW 
WHERE ST.PNAME = SW.PNAME AND DCOST= (SELECT MAX(DCOST) FROM software)

--98
SELECT DISTINCT PROF1 FROM programmer WHERE PROF1 NOT IN (SELECT DEVELOPIN FROM software) UNION
SELECT DISTINCT PROF2 FROM programmer WHERE PROF2 NOT IN (SELECT DEVELOPIN FROM software)

--99
SELECT T1.[SALARY], T2.[DEVELOPIN],T2.SOLD, T3.[COURSE] FROM PROGRAMMER AS T1 JOIN SOFTWARE AS T2 
ON T1.PNAME=T2.PNAME JOIN STUDIES AS T3 ON T2.PNAME=T3.PNAME 
WHERE SOLD= (SELECT MAX(SOLD) FROM software)


--100
select avg(Salary) from Programmer p JOIN Software s 
	ON p.PNAME=s.PNAME WHERE SOLD*SCOST >50000

--101

select distinct t2.[PNAME],[DEVELOPIN],[COURSE_FEE],[INSTITUTE],COUNT ( T1.[TITLE]) 
from [dbo].[software] as t1,[dbo].[studies] as t2
WHERE  COURSE_FEE = (SELECT MIN(COURSE_FEE) FROM Studies)
GROUP BY  T2.PNAME, DEVELOPIN,COURSE_FEE,INSTITUTE,TITLE


--102

SELECT TG.*, ST.INSTITUTE FROM studies AS ST INNER JOIN 
(
SELECT SW.PNAME, COUNT(TITLE) AS SWCNT 
--INSTITUTE 
FROM software AS SW 
--INNER JOIN studies AS ST ON SW.PNAME=ST.PNAME
WHERE SW.PNAME = (SELECT PNAME FROM software WHERE DCOST = (SELECT MIN(DCOST) FROM software)) 
GROUP BY SW.PNAME
) AS TG
ON ST.PNAME = TG.PNAME

--103
SELECT COUNT(TITLE) from Programmer p,Software s 
WHERE s.PNAME=p.PNAME and GENDER='F'
AND SALARY>(SELECT MAX(SALARY) FROM programmer WHERE GENDER='M')

--104
SELECT COUNT(TITLE) FROM software WHERE PNAME = 
(
	SELECT PG.PNAME, DOJ FROM programmer AS PG 
	WHERE DATEDIFF(DD,DOJ,GETDATE())= 
		(SELECT MAX(DATEDIFF(DD,DOJ,GETDATE())) 
		FROM programmer AS PG, studies AS ST
		WHERE PG.PNAME=ST.PNAME AND PG.PNAME IN (SELECT PNAME FROM studies WHERE INSTITUTE='BDPS'))
		AND PG.PNAME IN (SELECT PNAME FROM studies WHERE INSTITUTE='BDPS')
)

--105

SELECT PNAME,INSTITUTE from studies WHERE PNAME IN (SELECT PNAME from software)


--106
SELECT DEVELOPIN,sum(SCOST*SOLD-DCOST) AS PROFIT, COUNT(1) AS PROG_CNT from Software 
WHERE DEVELOPIN IN 
((SELECT PROF1 FROM Programmer) UNION ALL (SELECT PROF2 FROM Programmer))
GROUP BY DEVELOPIN

--107
SELECT PG.PNAME,count(TITLE) FROM programmer AS PG,software AS SW 
WHERE PG.PNAME=SW.PNAME GROUP BY PG.PNAME;